services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel/app
    container_name: dds_training-app
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
      - ./docker_config_files/php/local.ini:/usr/local/etc/php/conf.d/local.ini:delegated
      - ~/.composer/docker-cache/:/root/.composer:cached
    networks:
      - dds_training-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: dds_training-webserver
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www:delegated
      - ./docker_config_files/nginx/conf.d/:/etc/nginx/conf.d/:delegated
    networks:
      - dds_training-network
    depends_on:
      - postgres
      - app

  #Postgres Service
  postgres:
    container_name: dds_training-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres:delegated
    ports:
      - "5432:5432"
    networks:
      - dds_training-network

  #PgAdmin
  pgadmin:
    container_name: dds_training-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: administrador_carteira@email.com
      PGADMIN_DEFAULT_PASSWORD: carteira
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "8080:80"
    networks:
      - dds_training-network
    depends_on:
      - postgres

  #Composer
  composer:
    build:
      context: .
      dockerfile: Dockerfile-composer
    container_name: dds_training-composer
    volumes:
      - ./:/var/www/
    working_dir: /var/www/
    depends_on:
      - app
    networks:
      - dds_training-network

  #NPM
  npm:
    image: node:latest
    container_name: dds_training-npm
    volumes:
      - ./:/var/www/
    working_dir: /var/www/
    entrypoint: [ "npm" ]
    ports:
      - "5173:5173"
    networks:
      - dds_training-network

  #Artisan
  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dds_training-artisan
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
    working_dir: /var/www/
    entrypoint: [ "php", "/var/www/artisan" ]
    networks:
      - dds_training-network

#Docker Networks
networks:
  dds_training-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
  postgres:
  pgadmin:
